#!/usr/bin/env python3
"""Generate the HPP-ready scene assets for the SO-101 cube pick-and-place.

Writes into ``soarm_tamp/generated/``:

* ``so101.urdf``  — the vendored SO-101 description with every mesh
  reference rewritten to an absolute path. pinocchio resolves a relative
  ``filename=`` against the *process* CWD, not the URDF's own directory,
  so the vendored file only loads if you happen to run from the right
  place; rewriting removes that trap. Paths are *container*-absolute
  because pyhpp only exists inside the planning container.
* ``so101.srdf``  — HPP manipulation semantics: the ``<gripper>`` tag at
  the measured grasp frame, plus adjacent-link collision exclusions
  derived from the kinematic tree.
* ``cube.urdf`` / ``cube.srdf`` — a CUBE_SIZE_M box with one ``<handle>``
  carrying a 5-DOF mask (see the SRDF's own comment for why).
* ``table.urdf`` — the work surface, as a collision proxy.

Run inside or outside the container; it only reads/writes files.

    python -m soarm_tamp.build_assets
"""

from __future__ import annotations

import argparse
import xml.etree.ElementTree as ET
from pathlib import Path

from .geometry import (
    CUBE_SIZE_M,
    GRASP_CENTERLINE_X_M,
    GRASP_DEPTH_Z_M,
)

_HERE = Path(__file__).parent
GENERATED = _HERE / "generated"

# Where soarm-ws is mounted inside the planning container. The generated
# URDFs bake this in, so they are container artefacts and will not resolve
# their meshes if loaded from macOS.
CONTAINER_WS = "/home/thanhndv212/devel/soarm-ws"
VENDORED_REL = "SO-ARM100/Simulation/SO101"

# The table's collision box top sits this far *below* the robot base
# plane (z=0), which is the real mounting surface. A collision box whose
# face is exactly flush with a resting object reads as interpenetration to
# the checker, and because the table never moves that failure is constant
# rather than something retries can escape — the same trap the ikea
# prototype hit and documented. The cube's true resting height is
# unchanged; only the collision proxy is recessed.
TABLE_RECESS_M = 0.003

# Where the cube starts (A) and where it must end up (B), in metres, as
# (x, y) on the table. Both sit inside the top-down-reachable annulus
# measured in studies/reachability.py (radius 0.10-0.30 m): |A| = |B| =
# 0.242 m.
PICK_XY = (0.22, -0.10)
PLACE_XY = (0.22, 0.10)
TABLE_HALF_EXTENT_M = 0.45
TABLE_THICKNESS_M = 0.04


def _rewrite_mesh_paths(src: Path, dst: Path, mesh_root: str) -> int:
    """Copy *src* URDF to *dst*, making every mesh filename absolute."""
    tree = ET.parse(src)
    n = 0
    for mesh in tree.getroot().iter("mesh"):
        fn = mesh.get("filename")
        if fn and not fn.startswith("/"):
            mesh.set("filename", f"{mesh_root}/{fn}")
            n += 1
    dst.parent.mkdir(parents=True, exist_ok=True)
    tree.write(dst, encoding="utf-8", xml_declaration=True)
    return n


def _adjacent_pairs(urdf: Path) -> list[tuple[str, str]]:
    """Parent/child link pairs — always in contact, never worth checking."""
    root = ET.parse(urdf).getroot()
    return [
        (j.find("parent").get("link"), j.find("child").get("link"))
        for j in root.findall("joint")
    ]


def _write_robot_srdf(dst: Path, urdf: Path) -> None:
    pairs = _adjacent_pairs(urdf)
    # The jaw and the fixed finger touch at the hinge through their whole
    # travel, so the pair is permanently in collision by construction.
    extra = [("gripper_link", "moving_jaw_so101_v1_link")]
    lines = [
        '<?xml version="1.0"?>',
        "<!--",
        "  HPP manipulation semantics for the SO-101. Generated by",
        "  soarm_tamp/build_assets.py — edit that, not this file.",
        "",
        "  The <gripper> frame is gripper_frame_link shifted to the measured",
        "  grasp point (see soarm_tamp/geometry.py). Two offsets matter and",
        "  neither is zero:",
        "",
        f"    x = {GRASP_CENTERLINE_X_M:+.4f} m — the jaws are not symmetric about the",
        "      frame origin (moving jaw at -X, fixed finger at +X), so the",
        "      real centerline between them is offset. Grasping at the raw",
        "      origin would sit a 25 mm cube ~13 mm off-centre in a 29 mm",
        "      gap, i.e. against one finger.",
        f"    z = {GRASP_DEPTH_Z_M:+.4f} m — the frame origin is at the fingertips",
        "      (only 6 mm of finger lies beyond it); this seats the object",
        "      mid-finger instead of gripping it by the tips.",
        "-->",
        '<robot name="so101">',
    ]
    for a, b in pairs:
        lines.append(f'  <disable_collisions link1="{a}" link2="{b}" reason="Adjacent"/>')
    for a, b in extra:
        lines.append(f'  <disable_collisions link1="{a}" link2="{b}" reason="Default"/>')
    lines += [
        "",
        '  <!-- Named "grasp", not "gripper": the URDF already has a *joint*',
        '       called gripper, and HPP resolves a gripper tag by frame name --',
        '       the collision makes the SRDF fail to load outright. -->',
        '  <gripper name="grasp" clearance="0.03">',
        f'    <position xyz="{GRASP_CENTERLINE_X_M:.5f} 0 {GRASP_DEPTH_Z_M:.5f}" rpy="0 0 0"/>',
        '    <link name="gripper_frame_link"/>',
        "  </gripper>",
        "</robot>",
    ]
    dst.write_text("\n".join(lines) + "\n")


def _write_cube(urdf: Path, srdf: Path) -> None:
    s = CUBE_SIZE_M
    urdf.write_text(
        f"""<?xml version="1.0"?>
<!-- {s * 1000:.0f} mm cube. Generated by soarm_tamp/build_assets.py. -->
<robot name="cube">
  <link name="base_link">
    <visual>
      <geometry><box size="{s} {s} {s}"/></geometry>
      <material name="red"><color rgba="0.85 0.16 0.16 1"/></material>
    </visual>
    <collision>
      <geometry><box size="{s} {s} {s}"/></geometry>
    </collision>
    <inertial>
      <mass value="0.02"/>
      <inertia ixx="2.1e-6" ixy="0" ixz="0" iyy="2.1e-6" iyz="0" izz="2.1e-6"/>
    </inertial>
  </link>
</robot>
"""
    )
    srdf.write_text(
        f"""<?xml version="1.0"?>
<!--
  Grasp semantics for the cube. Generated by soarm_tamp/build_assets.py.

  Frame: at the cube centre, rotated pi about X so the handle's +Z points
  DOWN in the world while the cube rests on the table. At grasp the
  gripper frame coincides with this one, and the gripper's +Z is its
  approach direction — so a handle +Z pointing down is exactly a top-down
  grasp.

  <mask> 1 1 1 1 1 0 — position and two rotations constrained, rotation
  about the handle's own Z (the approach axis) left FREE. Two reasons:

  1. The SO-101 has 5 arm joints. A full 6-DOF grasp is 6 constraints, so
     a solution only exists where the constraint set happens to be
     degenerate. A 5-constraint grasp is exactly determined instead, which
     is the difference between a solver that usually converges and one
     that usually times out.
  2. It is the physically meaningless DOF here anyway: a parallel-jaw grip
     on a cube does not care how it is rotated about the approach axis.

  A 600k-sample sweep confirmed the arm has ~170 deg of usable yaw at every
  candidate cube spot, so freeing this DOF costs no reachability — see
  soarm_tamp/studies/reachability.py.
-->
<robot name="cube">
  <handle name="top" clearance="{CUBE_SIZE_M:.4f}" approaching_direction="0 0 1">
    <position xyz="0 0 0" rpy="3.14159265 0 0"/>
    <link name="base_link"/>
    <mask>1 1 1 1 1 0</mask>
  </handle>

  <!--
    The cube's own "gripper", at the centre of its bottom face. A gripper
    role on a carried object, not on a robot link — the same device the
    ikea prototype uses for legN/peg and agimus_spacelab for
    screw_driver's g_SD_part.

    It exists because releasing with a plain (gripper, None) leaves the
    object wherever the transport path happened to end: the drop spot is
    emergent, not chosen. Docking this frame onto a NAMED handle on the
    table instead makes "place at B" a value this scene sets.
  -->
  <gripper name="foot" clearance="0.02">
    <position xyz="0 0 {-CUBE_SIZE_M / 2:.5f}" rpy="3.14159265 0 0"/>
    <link name="base_link"/>
  </gripper>
</robot>
"""
    )


def _write_table_srdf(dst: Path) -> None:
    x, y = PLACE_XY
    dst.write_text(
        f"""<?xml version="1.0"?>
<!--
  The table's place-target semantics. Generated by build_assets.py.

  The table is loaded as a ROBOT (anchor root joint), not as an
  environment: SceneBuilder.load_environment takes no SRDF, so an
  environment cannot carry a handle. An anchored robot contributes zero
  joints to the configuration vector, so this costs nothing but makes
  spot_b addressable.

  spot_b is at the table surface (z=0, the real mounting plane) at the
  place location. The cube docks its `foot` frame here, which puts the
  centre of the cube's bottom face exactly on that spot.

  Same 5-DOF mask as the cube's handle, for the same reason plus one
  more: with the arm holding the cube, the chain is 5 arm joints + 6 cube
  freeflyer DOF against a 5-constraint grasp and this dock. Leaving the
  cube's yaw on the table free keeps a 1-dimensional solution manifold
  rather than forcing an isolated one — and which way round a cube sits
  on its spot is not something this task cares about.
-->
<robot name="table">
  <handle name="spot_b" clearance="0.03" approaching_direction="0 0 1">
    <position xyz="{x:.4f} {y:.4f} 0" rpy="3.14159265 0 0"/>
    <link name="base_link"/>
    <mask>1 1 1 1 1 0</mask>
  </handle>
</robot>
"""
    )


def _write_table(dst: Path) -> None:
    h, t = TABLE_HALF_EXTENT_M, TABLE_THICKNESS_M
    top = -TABLE_RECESS_M
    dst.write_text(
        f"""<?xml version="1.0"?>
<!--
  Work surface. Generated by soarm_tamp/build_assets.py.

  The real mounting surface is z=0 (the robot base plane). This collision
  box's top face is recessed {TABLE_RECESS_M * 1000:.0f} mm below it: a box face exactly flush
  with a resting object reads as interpenetration to the collision
  checker, and since the table never moves that would be a constant,
  unescapable failure rather than something a retry resolves.
-->
<robot name="table">
  <link name="base_link">
    <visual>
      <origin xyz="0 0 {top - t / 2:.4f}"/>
      <geometry><box size="{2 * h} {2 * h} {t}"/></geometry>
      <material name="grey"><color rgba="0.55 0.55 0.58 1"/></material>
    </visual>
    <collision>
      <origin xyz="0 0 {top - t / 2:.4f}"/>
      <geometry><box size="{2 * h} {2 * h} {t}"/></geometry>
    </collision>
  </link>
</robot>
"""
    )


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument(
        "--ws-root",
        default=CONTAINER_WS,
        help="soarm-ws root as seen by the consumer of these files "
        f"(default: the container path {CONTAINER_WS})",
    )
    args = ap.parse_args()

    GENERATED.mkdir(parents=True, exist_ok=True)
    vendored = Path(args.ws_root) / VENDORED_REL / "so101_new_calib.urdf"
    src = Path(_HERE.parent.parent) / VENDORED_REL / "so101_new_calib.urdf"
    if not src.exists():
        raise SystemExit(f"vendored SO-101 URDF not found: {src}")

    robot_urdf = GENERATED / "so101.urdf"
    n = _rewrite_mesh_paths(src, robot_urdf, f"{args.ws_root}/{VENDORED_REL}")
    _write_robot_srdf(GENERATED / "so101.srdf", src)
    _write_cube(GENERATED / "cube.urdf", GENERATED / "cube.srdf")
    _write_table(GENERATED / "table.urdf")
    _write_table_srdf(GENERATED / "table.srdf")

    print(f"vendored source : {vendored}")
    print(f"wrote {robot_urdf.name:12s} ({n} mesh paths made absolute)")
    for f in ("so101.srdf", "cube.urdf", "cube.srdf", "table.urdf", "table.srdf"):
        print(f"wrote {f}")
    print(f"\ngenerated/ -> {GENERATED}")


if __name__ == "__main__":
    main()
